[package]
name = "one-thousand-deaths"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"		# datetime library
slog = "2.7.0"			# structured logging
sloggers = "2.1.1"		# slog convenience functions
# slog-term = "2.8.0"		# logging to a terminal/console/shell or other text based dest
termion = "1.5.6"		# terminal support
