[package]
name = "onek-deaths"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arraystring = { version = "0.3.0", features = [
    "serde-traits",
] } # fixed capacity strings
chrono = "0.4.39" # time library
clap = { version = "4.5.27", features = ["derive"] } # command line parser
crossterm = "0.28.1" # cross-platform terminal library
log = "0.4.25" # simpler logging API
fnv = "1.0.7" # custom hasher that is much more performant for small keys
postcard = { version = "1.1.1", features = [
    "alloc",
] } # binary backend for serde
serde = { version = "1.0.217", features = ["derive"] } # serialization framework
serde_derive = "1.0.217" # serde derive macros
simplelog = "0.12.2" # logging facade

[dev-dependencies]
insta = { version = "1.41.1", features = ["yaml"] }

# Better profiling in release TODO: set this to false
[profile.release]
debug = true
