[package]
name = "one-thousand-deaths"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"	    # datetime library
derive_more = "0.99.17" # helper to derive traits like Display for structs and enums
fnv = "1.0.7"	        # custom hasher that is much more performant for small keys
log = "0.4.14" 	        # logging facade
simplelog = "0.11.2" 	# logging to a file
termion = "1.5.6"       # terminal support
