[package]
name = "onek-deaths"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.39"                                    # time library
clap = { version = "4.5.27", features = ["derive"] } # command line parser
crossterm = "0.28.1"                                 # cross-platform terminal library
log = "0.4.25"                                       # simpler logging API
fnv = "1.0.7"                                        # custom hasher that is much more performant for small keys
simplelog = "0.12.2"                                 # logging facade

# byteorder = "1.5.0" # byte-swapping library
# ipmpsc = "0.5.1" # inter-process channels
# postcard = { version = "1.0.8", features = [
#     "alloc",
# ] } # binary backend for serde
# serde = { version = "1.0.195", features = ["derive"] } # serialization framework
# serde_derive = "1.0.195" # serde derive macros

# Better profiling in release TODO: set this to false
[profile.release]
debug = true
