use crossterm::style;

// These are the X11 color names (from https://www.cgl.ucsf.edu/chimerax/docs/user/commands/colornames.html).
#[allow(dead_code)]
#[derive(Clone, Copy, Debug)]
pub enum Color {
    MediumVioletRed,
    DeepPink,
    PaleVioletRed,
    HotPink,
    LightPink,
    Pink,
    DarkRed,
    Red,
    Firebrick,
    Crimson,
    IndianRed,
    LightCoral,
    Salmon,
    DarkSalmon,
    LightSalmon,
    OrangeRed,
    Tomato,
    DarkOrange,
    Coral,
    Orange,
    DarkKhaki,
    Gold,
    Khaki,
    PeachPuff,
    Yellow,
    PaleGoldenrod,
    Moccasin,
    PapayaWhip,
    LightGoldenrodYellow,
    LemonChiffon,
    LightYellow,
    Maroon,
    Brown,
    SaddleBrown,
    Sienna,
    Chocolate,
    DarkGoldenrod,
    Peru,
    RosyBrown,
    Goldenrod,
    SandyBrown,
    Tan,
    Burlywood,
    Wheat,
    NavajoWhite,
    Bisque,
    BlanchedAlmond,
    Cornsilk,
    Indigo,
    Purple,
    DarkMagenta,
    DarkViolet,
    DarkSlateBlue,
    BlueViolet,
    DarkOrchid,
    Fuchsia,
    Magenta,
    SlateBlue,
    MediumSlateBlue,
    MediumOrchid,
    MediumPurple,
    Orchid,
    Violet,
    Plum,
    Thistle,
    Lavender,
    MidnightBlue,
    Navy,
    DarkBlue,
    MediumBlue,
    Blue,
    RoyalBlue,
    SteelBlue,
    DodgerBlue,
    DeepSkyBlue,
    CornflowerBlue,
    SkyBlue,
    LightSkyBlue,
    LightSteelBlue,
    LightBlue,
    PowderBlue,
    Teal,
    DarkCyan,
    LightSeaGreen,
    CadetBlue,
    DarkTurquoise,
    MediumTurquoise,
    Turquoise,
    Aqua,
    Cyan,
    Aquamarine,
    PaleTurquoise,
    LightCyan,
    DarkGreen,
    Green,
    DarkOliveGreen,
    ForestGreen,
    SeaGreen,
    Olive,
    OliveDrab,
    MediumSeaGreen,
    LimeGreen,
    Lime,
    SpringGreen,
    MediumSpringGreen,
    DarkSeaGreen,
    MediumAquamarine,
    YellowGreen,
    LawnGreen,
    Chartreuse,
    LightGreen,
    GreenYellow,
    PaleGreen,
    MistyRose,
    AntiqueWhite,
    Linen,
    Beige,
    WhiteSmoke,
    LavenderBlush,
    OldLace,
    AliceBlue,
    Seashell,
    GhostWhite,
    Honeydew,
    FloralWhite,
    Azure,
    MintCream,
    Snow,
    Ivory,
    White,
    Black,
    DarkSlateGray,
    DimGray,
    SlateGray,
    Gray,
    LightSlateGray,
    DarkGray,
    Silver,
    LightGray,
    Gainsboro,
}

/// See https://www.cgl.ucsf.edu/chimerax/docs/user/commands/colornames.html
/// and https://en.wikipedia.org/wiki/Web_colors#X11_color_names
pub fn to_crossterm(color: Color) -> style::Color {
    use Color::*;
    match color {
        MediumVioletRed => style::Color::Rgb { r: 199, g: 21, b: 133 },
        DeepPink => style::Color::Rgb { r: 255, g: 20, b: 147 },
        PaleVioletRed => style::Color::Rgb { r: 219, g: 112, b: 147 },
        HotPink => style::Color::Rgb { r: 255, g: 105, b: 180 },
        LightPink => style::Color::Rgb { r: 255, g: 182, b: 193 },
        Pink => style::Color::Rgb { r: 255, g: 192, b: 203 },
        DarkRed => style::Color::Rgb { r: 139, g: 0, b: 0 },
        Red => style::Color::Rgb { r: 255, g: 0, b: 0 },
        Firebrick => style::Color::Rgb { r: 178, g: 34, b: 34 },
        Crimson => style::Color::Rgb { r: 220, g: 20, b: 60 },
        IndianRed => style::Color::Rgb { r: 205, g: 92, b: 92 },
        LightCoral => style::Color::Rgb { r: 240, g: 128, b: 128 },
        Salmon => style::Color::Rgb { r: 250, g: 128, b: 114 },
        DarkSalmon => style::Color::Rgb { r: 233, g: 150, b: 122 },
        LightSalmon => style::Color::Rgb { r: 255, g: 160, b: 122 },
        OrangeRed => style::Color::Rgb { r: 255, g: 69, b: 0 },
        Tomato => style::Color::Rgb { r: 255, g: 99, b: 71 },
        DarkOrange => style::Color::Rgb { r: 255, g: 140, b: 0 },
        Coral => style::Color::Rgb { r: 255, g: 127, b: 80 },
        Orange => style::Color::Rgb { r: 255, g: 165, b: 0 },
        DarkKhaki => style::Color::Rgb { r: 189, g: 183, b: 107 },
        Gold => style::Color::Rgb { r: 255, g: 215, b: 0 },
        Khaki => style::Color::Rgb { r: 240, g: 230, b: 140 },
        PeachPuff => style::Color::Rgb { r: 255, g: 218, b: 185 },
        Yellow => style::Color::Rgb { r: 255, g: 255, b: 0 },
        PaleGoldenrod => style::Color::Rgb { r: 238, g: 232, b: 170 },
        Moccasin => style::Color::Rgb { r: 255, g: 228, b: 181 },
        PapayaWhip => style::Color::Rgb { r: 255, g: 239, b: 213 },
        LightGoldenrodYellow => style::Color::Rgb { r: 250, g: 250, b: 210 },
        LemonChiffon => style::Color::Rgb { r: 255, g: 250, b: 205 },
        LightYellow => style::Color::Rgb { r: 255, g: 255, b: 224 },
        Maroon => style::Color::Rgb { r: 128, g: 0, b: 0 },
        Brown => style::Color::Rgb { r: 165, g: 42, b: 42 },
        SaddleBrown => style::Color::Rgb { r: 139, g: 69, b: 19 },
        Sienna => style::Color::Rgb { r: 160, g: 82, b: 45 },
        Chocolate => style::Color::Rgb { r: 210, g: 105, b: 30 },
        DarkGoldenrod => style::Color::Rgb { r: 184, g: 134, b: 11 },
        Peru => style::Color::Rgb { r: 205, g: 133, b: 63 },
        RosyBrown => style::Color::Rgb { r: 188, g: 143, b: 143 },
        Goldenrod => style::Color::Rgb { r: 218, g: 165, b: 32 },
        SandyBrown => style::Color::Rgb { r: 244, g: 164, b: 96 },
        Tan => style::Color::Rgb { r: 210, g: 180, b: 140 },
        Burlywood => style::Color::Rgb { r: 222, g: 184, b: 135 },
        Wheat => style::Color::Rgb { r: 245, g: 222, b: 179 },
        NavajoWhite => style::Color::Rgb { r: 255, g: 222, b: 173 },
        Bisque => style::Color::Rgb { r: 255, g: 228, b: 196 },
        BlanchedAlmond => style::Color::Rgb { r: 255, g: 235, b: 205 },
        Cornsilk => style::Color::Rgb { r: 255, g: 248, b: 220 },
        Indigo => style::Color::Rgb { r: 75, g: 0, b: 130 },
        Purple => style::Color::Rgb { r: 128, g: 0, b: 128 },
        DarkMagenta => style::Color::Rgb { r: 139, g: 0, b: 139 },
        DarkViolet => style::Color::Rgb { r: 148, g: 0, b: 211 },
        DarkSlateBlue => style::Color::Rgb { r: 72, g: 61, b: 139 },
        BlueViolet => style::Color::Rgb { r: 138, g: 43, b: 226 },
        DarkOrchid => style::Color::Rgb { r: 153, g: 50, b: 204 },
        Fuchsia => style::Color::Rgb { r: 255, g: 0, b: 255 },
        Magenta => style::Color::Rgb { r: 255, g: 0, b: 255 },
        SlateBlue => style::Color::Rgb { r: 106, g: 90, b: 205 },
        MediumSlateBlue => style::Color::Rgb { r: 123, g: 104, b: 238 },
        MediumOrchid => style::Color::Rgb { r: 186, g: 85, b: 211 },
        MediumPurple => style::Color::Rgb { r: 147, g: 112, b: 219 },
        Orchid => style::Color::Rgb { r: 218, g: 112, b: 214 },
        Violet => style::Color::Rgb { r: 238, g: 130, b: 238 },
        Plum => style::Color::Rgb { r: 221, g: 160, b: 221 },
        Thistle => style::Color::Rgb { r: 216, g: 191, b: 216 },
        Lavender => style::Color::Rgb { r: 230, g: 230, b: 250 },
        MidnightBlue => style::Color::Rgb { r: 25, g: 25, b: 112 },
        Navy => style::Color::Rgb { r: 0, g: 0, b: 128 },
        DarkBlue => style::Color::Rgb { r: 0, g: 0, b: 139 },
        MediumBlue => style::Color::Rgb { r: 0, g: 0, b: 205 },
        Blue => style::Color::Rgb { r: 0, g: 0, b: 255 },
        RoyalBlue => style::Color::Rgb { r: 65, g: 105, b: 225 },
        SteelBlue => style::Color::Rgb { r: 70, g: 130, b: 180 },
        DodgerBlue => style::Color::Rgb { r: 30, g: 144, b: 255 },
        DeepSkyBlue => style::Color::Rgb { r: 0, g: 191, b: 255 },
        CornflowerBlue => style::Color::Rgb { r: 100, g: 149, b: 237 },
        SkyBlue => style::Color::Rgb { r: 135, g: 206, b: 235 },
        LightSkyBlue => style::Color::Rgb { r: 135, g: 206, b: 250 },
        LightSteelBlue => style::Color::Rgb { r: 176, g: 196, b: 222 },
        LightBlue => style::Color::Rgb { r: 173, g: 216, b: 230 },
        PowderBlue => style::Color::Rgb { r: 176, g: 224, b: 230 },
        Teal => style::Color::Rgb { r: 0, g: 128, b: 128 },
        DarkCyan => style::Color::Rgb { r: 0, g: 139, b: 139 },
        LightSeaGreen => style::Color::Rgb { r: 32, g: 178, b: 170 },
        CadetBlue => style::Color::Rgb { r: 95, g: 158, b: 160 },
        DarkTurquoise => style::Color::Rgb { r: 0, g: 206, b: 209 },
        MediumTurquoise => style::Color::Rgb { r: 72, g: 209, b: 204 },
        Turquoise => style::Color::Rgb { r: 64, g: 224, b: 208 },
        Aqua => style::Color::Rgb { r: 0, g: 255, b: 255 },
        Cyan => style::Color::Rgb { r: 0, g: 255, b: 255 },
        Aquamarine => style::Color::Rgb { r: 127, g: 255, b: 212 },
        PaleTurquoise => style::Color::Rgb { r: 175, g: 238, b: 238 },
        LightCyan => style::Color::Rgb { r: 224, g: 255, b: 255 },
        DarkGreen => style::Color::Rgb { r: 0, g: 100, b: 0 },
        Green => style::Color::Rgb { r: 0, g: 128, b: 0 },
        DarkOliveGreen => style::Color::Rgb { r: 85, g: 107, b: 47 },
        ForestGreen => style::Color::Rgb { r: 34, g: 139, b: 34 },
        SeaGreen => style::Color::Rgb { r: 46, g: 139, b: 87 },
        Olive => style::Color::Rgb { r: 128, g: 128, b: 0 },
        OliveDrab => style::Color::Rgb { r: 107, g: 142, b: 35 },
        MediumSeaGreen => style::Color::Rgb { r: 60, g: 179, b: 113 },
        LimeGreen => style::Color::Rgb { r: 50, g: 205, b: 50 },
        Lime => style::Color::Rgb { r: 0, g: 255, b: 0 },
        SpringGreen => style::Color::Rgb { r: 0, g: 255, b: 127 },
        MediumSpringGreen => style::Color::Rgb { r: 0, g: 250, b: 154 },
        DarkSeaGreen => style::Color::Rgb { r: 143, g: 188, b: 143 },
        MediumAquamarine => style::Color::Rgb { r: 102, g: 205, b: 170 },
        YellowGreen => style::Color::Rgb { r: 154, g: 205, b: 50 },
        LawnGreen => style::Color::Rgb { r: 124, g: 252, b: 0 },
        Chartreuse => style::Color::Rgb { r: 127, g: 255, b: 0 },
        LightGreen => style::Color::Rgb { r: 144, g: 238, b: 144 },
        GreenYellow => style::Color::Rgb { r: 173, g: 255, b: 47 },
        PaleGreen => style::Color::Rgb { r: 152, g: 251, b: 152 },
        MistyRose => style::Color::Rgb { r: 255, g: 228, b: 225 },
        AntiqueWhite => style::Color::Rgb { r: 250, g: 235, b: 215 },
        Linen => style::Color::Rgb { r: 250, g: 240, b: 230 },
        Beige => style::Color::Rgb { r: 245, g: 245, b: 220 },
        WhiteSmoke => style::Color::Rgb { r: 245, g: 245, b: 245 },
        LavenderBlush => style::Color::Rgb { r: 255, g: 240, b: 245 },
        OldLace => style::Color::Rgb { r: 253, g: 245, b: 230 },
        AliceBlue => style::Color::Rgb { r: 240, g: 248, b: 255 },
        Seashell => style::Color::Rgb { r: 255, g: 245, b: 238 },
        GhostWhite => style::Color::Rgb { r: 248, g: 248, b: 255 },
        Honeydew => style::Color::Rgb { r: 240, g: 255, b: 240 },
        FloralWhite => style::Color::Rgb { r: 255, g: 250, b: 240 },
        Azure => style::Color::Rgb { r: 240, g: 255, b: 255 },
        MintCream => style::Color::Rgb { r: 245, g: 255, b: 250 },
        Snow => style::Color::Rgb { r: 255, g: 250, b: 250 },
        Ivory => style::Color::Rgb { r: 255, g: 255, b: 240 },
        White => style::Color::Rgb { r: 255, g: 255, b: 255 },
        Black => style::Color::Rgb { r: 0, g: 0, b: 0 },
        DarkSlateGray => style::Color::Rgb { r: 47, g: 79, b: 79 },
        DimGray => style::Color::Rgb { r: 105, g: 105, b: 105 },
        SlateGray => style::Color::Rgb { r: 112, g: 128, b: 144 },
        Gray => style::Color::Rgb { r: 128, g: 128, b: 128 },
        LightSlateGray => style::Color::Rgb { r: 119, g: 136, b: 153 },
        DarkGray => style::Color::Rgb { r: 169, g: 169, b: 169 },
        Silver => style::Color::Rgb { r: 192, g: 192, b: 192 },
        LightGray => style::Color::Rgb { r: 211, g: 211, b: 211 },
        Gainsboro => style::Color::Rgb { r: 220, g: 220, b: 220 },
    }
}
