use serde::{Deserialize, Serialize};

// These are the X11 color names (from http://cng.seas.rochester.edu/CNG/docs/x11color.html).
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
pub enum Color {
    LightPink,
    Pink,
    Crimson,
    LavenderBlush,
    PaleVioletRed,
    HotPink,
    DeepPink,
    MediumVioletRed,
    Orchid,
    Thistle,
    Plum,
    Violet,
    Magenta,
    Fuchsia,
    DarkMagenta,
    Purple,
    MediumOrchid,
    DarkViolet,
    DarkOrchid,
    Indigo,
    BlueViolet,
    MediumPurple,
    MediumSlateBlue,
    SlateBlue,
    DarkSlateBlue,
    Lavender,
    GhostWhite,
    Blue,
    MediumBlue,
    MidnightBlue,
    DarkBlue,
    Navy,
    RoyalBlue,
    CornflowerBlue,
    LightSteelBlue,
    LightSlateGray,
    SlateGray,
    DodgerBlue,
    AliceBlue,
    SteelBlue,
    LightSkyBlue,
    SkyBlue,
    DeepSkyBlue,
    LightBlue,
    PowderBlue,
    CadetBlue,
    Azure,
    LightCyan,
    PaleTurquoise,
    Cyan,
    Aqua,
    DarkTurquoise,
    DarkSlateGray,
    DarkCyan,
    Teal,
    MediumTurquoise,
    LightSeaGreen,
    Turquoise,
    Aquamarine,
    MediumAquamarine,
    MediumSpringGreen,
    MintCream,
    SpringGreen,
    MediumSeaGreen,
    SeaGreen,
    Honeydew,
    LightGreen,
    PaleGreen,
    DarkSeaGreen,
    LimeGreen,
    Lime,
    ForestGreen,
    Green,
    DarkGreen,
    Chartreuse,
    LawnGreen,
    GreenYellow,
    DarkOliveGreen,
    YellowGreen,
    OliveDrab,
    Beige,
    LightGoldenrodYellow,
    Ivory,
    LightYellow,
    Yellow,
    Olive,
    DarkKhaki,
    LemonChiffon,
    PaleGoldenrod,
    Khaki,
    Gold,
    Cornsilk,
    Goldenrod,
    DarkGoldenrod,
    FloralWhite,
    OldLace,
    Wheat,
    Moccasin,
    Orange,
    PapayaWhip,
    BlanchedAlmond,
    NavajoWhite,
    AntiqueWhite,
    Tan,
    BurlyWood,
    Bisque,
    DarkOrange,
    Linen,
    Peru,
    PeachPuff,
    SandyBrown,
    Chocolate,
    SaddleBrown,
    Seashell,
    Sienna,
    LightSalmon,
    Coral,
    OrangeRed,
    DarkSalmon,
    Tomato,
    MistyRose,
    Salmon,
    Snow,
    LightCoral,
    RosyBrown,
    IndianRed,
    Red,
    Brown,
    FireBrick,
    DarkRed,
    Maroon,
    White,
    WhiteSmoke,
    Gainsboro,
    LightGrey,
    Silver,
    DarkGray,
    Gray,
    DimGray,
    Black,
}

impl Color {
    pub fn new(name: &str) -> Color {
        let name = name.to_lowercase();
        match name.as_str() {
            "lightpink" => Color::LightPink,
            "pink" => Color::Pink,
            "crimson" => Color::Crimson,
            "lavenderblush" => Color::LavenderBlush,
            "palevioletred" => Color::PaleVioletRed,
            "hotpink" => Color::HotPink,
            "deeppink" => Color::DeepPink,
            "mediumvioletred" => Color::MediumVioletRed,
            "orchid" => Color::Orchid,
            "thistle" => Color::Thistle,
            "plum" => Color::Plum,
            "violet" => Color::Violet,
            "magenta" => Color::Magenta,
            "fuchsia" => Color::Fuchsia,
            "darkmagenta" => Color::DarkMagenta,
            "purple" => Color::Purple,
            "mediumorchid" => Color::MediumOrchid,
            "darkviolet" => Color::DarkViolet,
            "darkorchid" => Color::DarkOrchid,
            "indigo" => Color::Indigo,
            "blueviolet" => Color::BlueViolet,
            "mediumpurple" => Color::MediumPurple,
            "mediumslateblue" => Color::MediumSlateBlue,
            "slateblue" => Color::SlateBlue,
            "darkslateblue" => Color::DarkSlateBlue,
            "lavender" => Color::Lavender,
            "ghostwhite" => Color::GhostWhite,
            "blue" => Color::Blue,
            "mediumblue" => Color::MediumBlue,
            "midnightblue" => Color::MidnightBlue,
            "darkblue" => Color::DarkBlue,
            "navy" => Color::Navy,
            "royalblue" => Color::RoyalBlue,
            "cornflowerblue" => Color::CornflowerBlue,
            "lightsteelblue" => Color::LightSteelBlue,
            "lightslategray" => Color::LightSlateGray,
            "slategray" => Color::SlateGray,
            "dodgerblue" => Color::DodgerBlue,
            "aliceblue" => Color::AliceBlue,
            "steelblue" => Color::SteelBlue,
            "lightskyblue" => Color::LightSkyBlue,
            "skyblue" => Color::SkyBlue,
            "deepskyblue" => Color::DeepSkyBlue,
            "lightblue" => Color::LightBlue,
            "powderblue" => Color::PowderBlue,
            "cadetblue" => Color::CadetBlue,
            "azure" => Color::Azure,
            "lightcyan" => Color::LightCyan,
            "paleturquoise" => Color::PaleTurquoise,
            "cyan" => Color::Cyan,
            "aqua" => Color::Aqua,
            "darkturquoise" => Color::DarkTurquoise,
            "darkslategray" => Color::DarkSlateGray,
            "darkcyan" => Color::DarkCyan,
            "teal" => Color::Teal,
            "mediumturquoise" => Color::MediumTurquoise,
            "lightseagreen" => Color::LightSeaGreen,
            "turquoise" => Color::Turquoise,
            "aquamarine" => Color::Aquamarine,
            "mediumaquamarine" => Color::MediumAquamarine,
            "mediumspringgreen" => Color::MediumSpringGreen,
            "mintcream" => Color::MintCream,
            "springgreen" => Color::SpringGreen,
            "mediumseagreen" => Color::MediumSeaGreen,
            "seagreen" => Color::SeaGreen,
            "honeydew" => Color::Honeydew,
            "lightgreen" => Color::LightGreen,
            "palegreen" => Color::PaleGreen,
            "darkseagreen" => Color::DarkSeaGreen,
            "limegreen" => Color::LimeGreen,
            "lime" => Color::Lime,
            "forestgreen" => Color::ForestGreen,
            "green" => Color::Green,
            "darkgreen" => Color::DarkGreen,
            "chartreuse" => Color::Chartreuse,
            "lawngreen" => Color::LawnGreen,
            "greenyellow" => Color::GreenYellow,
            "darkolivegreen" => Color::DarkOliveGreen,
            "yellowgreen" => Color::YellowGreen,
            "olivedrab" => Color::OliveDrab,
            "beige" => Color::Beige,
            "lightgoldenrodyellow" => Color::LightGoldenrodYellow,
            "ivory" => Color::Ivory,
            "lightyellow" => Color::LightYellow,
            "yellow" => Color::Yellow,
            "olive" => Color::Olive,
            "darkkhaki" => Color::DarkKhaki,
            "lemonchiffon" => Color::LemonChiffon,
            "palegoldenrod" => Color::PaleGoldenrod,
            "khaki" => Color::Khaki,
            "gold" => Color::Gold,
            "cornsilk" => Color::Cornsilk,
            "goldenrod" => Color::Goldenrod,
            "darkgoldenrod" => Color::DarkGoldenrod,
            "floralwhite" => Color::FloralWhite,
            "oldlace" => Color::OldLace,
            "wheat" => Color::Wheat,
            "moccasin" => Color::Moccasin,
            "orange" => Color::Orange,
            "papayawhip" => Color::PapayaWhip,
            "blanchedalmond" => Color::BlanchedAlmond,
            "navajowhite" => Color::NavajoWhite,
            "antiquewhite" => Color::AntiqueWhite,
            "tan" => Color::Tan,
            "burlywood" => Color::BurlyWood,
            "bisque" => Color::Bisque,
            "darkorange" => Color::DarkOrange,
            "linen" => Color::Linen,
            "peru" => Color::Peru,
            "peachpuff" => Color::PeachPuff,
            "sandybrown" => Color::SandyBrown,
            "chocolate" => Color::Chocolate,
            "saddlebrown" => Color::SaddleBrown,
            "seashell" => Color::Seashell,
            "sienna" => Color::Sienna,
            "lightsalmon" => Color::LightSalmon,
            "coral" => Color::Coral,
            "orangered" => Color::OrangeRed,
            "darksalmon" => Color::DarkSalmon,
            "tomato" => Color::Tomato,
            "mistyrose" => Color::MistyRose,
            "salmon" => Color::Salmon,
            "snow" => Color::Snow,
            "lightcoral" => Color::LightCoral,
            "rosybrown" => Color::RosyBrown,
            "indianred" => Color::IndianRed,
            "red" => Color::Red,
            "brown" => Color::Brown,
            "firebrick" => Color::FireBrick,
            "darkred" => Color::DarkRed,
            "maroon" => Color::Maroon,
            "white" => Color::White,
            "whitesmoke" => Color::WhiteSmoke,
            "gainsboro" => Color::Gainsboro,
            "lightgrey" => Color::LightGrey,
            "silver" => Color::Silver,
            "darkgray" => Color::DarkGray,
            "gray" => Color::Gray,
            "dimgray" => Color::DimGray,
            "black" => Color::Black,
            _ => panic!("'{name}' isn't an X11 color name"),
        }
    }
}
