use crossterm::style;

// These are the Xterm color names (from https://www.ditig.com/publications/256-colors-cheat-sheet).
#[allow(dead_code)]
#[derive(Clone, Copy, Debug)]
pub enum Color {
    // X11 color names are quite a bit nicer but style::Color::Rgb doesn't work well on Mac
    Black,
    Maroon,
    Green,
    Olive,
    Navy,
    Teal,
    Silver,
    Grey,
    Red,
    Lime,
    Yellow,
    Blue,
    Fuchsia,
    Aqua,
    White,
    Grey0,
    NavyBlue,
    DarkBlue,
    Blue3,
    Blue1,
    DarkGreen,
    DeepSkyBlue4,
    DodgerBlue3,
    DodgerBlue2,
    Green4,
    SpringGreen4,
    Turquoise4,
    DeepSkyBlue3,
    DodgerBlue1,
    DarkCyan,
    LightSeaGreen,
    DeepSkyBlue2,
    DeepSkyBlue1,
    Green3,
    SpringGreen3,
    Cyan3,
    DarkTurquoise,
    Turquoise2,
    Green1,
    SpringGreen2,
    SpringGreen1,
    MediumSpringGreen,
    Cyan2,
    Cyan1,
    Purple4,
    Purple3,
    BlueViolet,
    Grey37,
    MediumPurple4,
    SlateBlue3,
    RoyalBlue1,
    Chartreuse4,
    PaleTurquoise4,
    SteelBlue,
    SteelBlue3,
    CornflowerBlue,
    DarkSeaGreen4,
    CadetBlue,
    SkyBlue3,
    Chartreuse3,
    SeaGreen3,
    Aquamarine3,
    MediumTurquoise,
    SteelBlue1,
    SeaGreen2,
    SeaGreen1,
    DarkSlateGray2,
    DarkRed,
    DeepPink4,
    DarkMagenta,
    DarkViolet,
    Orange4,
    LightPink4,
    Plum4,
    MediumPurple3,
    SlateBlue1,
    Wheat4,
    Grey53,
    LightSlateGrey,
    MediumPurple,
    LightSlateBlue,
    Yellow4,
    DarkOliveGreen3,
    DarkSeaGreen,
    LightSkyBlue3,
    SkyBlue2,
    Chartreuse2,
    PaleGreen3,
    DarkSeaGreen3,
    DarkSlateGray3,
    SkyBlue1,
    Chartreuse1,
    LightGreen,
    Aquamarine1,
    DarkSlateGray1,
    MediumVioletRed,
    Purple,
    MediumOrchid3,
    MediumOrchid,
    DarkGoldenrod,
    RosyBrown,
    Grey63,
    MediumPurple2,
    MediumPurple1,
    DarkKhaki,
    NavajoWhite3,
    Grey69,
    LightSteelBlue3,
    LightSteelBlue,
    LightCyan3,
    LightSkyBlue1,
    GreenYellow,
    DarkOliveGreen2,
    PaleGreen1,
    DarkSeaGreen2,
    PaleTurquoise1,
    Red3,
    DeepPink3,
    Magenta3,
    DarkOrange3,
    IndianRed,
    HotPink3,
    HotPink2,
    Orchid,
    Orange3,
    LightSalmon3,
    LightPink3,
    Pink3,
    Plum3,
    Violet,
    Gold3,
    LightGoldenrod3,
    Tan,
    MistyRose3,
    Thistle3,
    Plum2,
    Yellow3,
    Khaki3,
    LightYellow3,
    Grey84,
    LightSteelBlue1,
    Yellow2,
    DarkOliveGreen1,
    DarkSeaGreen1,
    Honeydew2,
    LightCyan1,
    Red1,
    DeepPink2,
    DeepPink1,
    Magenta2,
    Magenta1,
    OrangeRed1,
    IndianRed1,
    HotPink,
    MediumOrchid1,
    DarkOrange,
    Salmon1,
    LightCoral,
    PaleVioletRed1,
    Orchid2,
    Orchid1,
    Orange1,
    SandyBrown,
    LightSalmon1,
    LightPink1,
    Pink1,
    Plum1,
    Gold1,
    LightGoldenrod2,
    NavajoWhite1,
    MistyRose1,
    Thistle1,
    Yellow1,
    LightGoldenrod1,
    Khaki1,
    Wheat1,
    Cornsilk1,
    Grey100,
    Grey3,
    Grey7,
    Grey11,
    Grey15,
    Grey19,
    Grey23,
    Grey27,
    Grey30,
    Grey35,
    Grey39,
    Grey42,
    Grey46,
    Grey50,
    Grey54,
    Grey58,
    Grey62,
    Grey66,
    Grey70,
    Grey74,
    Grey78,
    Grey82,
    Grey85,
    Grey89,
    Grey93,
}

pub fn to_crossterm(color: Color) -> style::Color {
    use Color::*;
    match color {
        Black => style::Color::AnsiValue(0),
        Maroon => style::Color::AnsiValue(1),
        Green => style::Color::AnsiValue(2),
        Olive => style::Color::AnsiValue(3),
        Navy => style::Color::AnsiValue(4),
        // Purple => style::Color::AnsiValue(5),
        Teal => style::Color::AnsiValue(6),
        Silver => style::Color::AnsiValue(7),
        Grey => style::Color::AnsiValue(8),
        Red => style::Color::AnsiValue(9),
        Lime => style::Color::AnsiValue(10),
        Yellow => style::Color::AnsiValue(11),
        Blue => style::Color::AnsiValue(12),
        Fuchsia => style::Color::AnsiValue(13),
        Aqua => style::Color::AnsiValue(14),
        White => style::Color::AnsiValue(15),
        Grey0 => style::Color::AnsiValue(16),
        NavyBlue => style::Color::AnsiValue(17),
        DarkBlue => style::Color::AnsiValue(18),
        // Blue3 => style::Color::AnsiValue(19),
        Blue3 => style::Color::AnsiValue(20),
        Blue1 => style::Color::AnsiValue(21),
        DarkGreen => style::Color::AnsiValue(22),
        // DeepSkyBlue4 => style::Color::AnsiValue(23),
        // DeepSkyBlue4 => style::Color::AnsiValue(24),
        DeepSkyBlue4 => style::Color::AnsiValue(25),
        DodgerBlue3 => style::Color::AnsiValue(26),
        DodgerBlue2 => style::Color::AnsiValue(27),
        Green4 => style::Color::AnsiValue(28),
        SpringGreen4 => style::Color::AnsiValue(29),
        Turquoise4 => style::Color::AnsiValue(30),
        // DeepSkyBlue3 => style::Color::AnsiValue(31),
        DeepSkyBlue3 => style::Color::AnsiValue(32),
        DodgerBlue1 => style::Color::AnsiValue(33),
        // Green3 => style::Color::AnsiValue(34),
        // SpringGreen3 => style::Color::AnsiValue(35),
        DarkCyan => style::Color::AnsiValue(36),
        LightSeaGreen => style::Color::AnsiValue(37),
        DeepSkyBlue2 => style::Color::AnsiValue(38),
        DeepSkyBlue1 => style::Color::AnsiValue(39),
        Green3 => style::Color::AnsiValue(40),
        SpringGreen3 => style::Color::AnsiValue(41),
        // SpringGreen2 => style::Color::AnsiValue(42),
        Cyan3 => style::Color::AnsiValue(43),
        DarkTurquoise => style::Color::AnsiValue(44),
        Turquoise2 => style::Color::AnsiValue(45),
        Green1 => style::Color::AnsiValue(46),
        SpringGreen2 => style::Color::AnsiValue(47),
        SpringGreen1 => style::Color::AnsiValue(48),
        MediumSpringGreen => style::Color::AnsiValue(49),
        Cyan2 => style::Color::AnsiValue(50),
        Cyan1 => style::Color::AnsiValue(51),
        // DarkRed => style::Color::AnsiValue(52),
        // DeepPink4 => style::Color::AnsiValue(53),
        // Purple4 => style::Color::AnsiValue(54),
        Purple4 => style::Color::AnsiValue(55),
        Purple3 => style::Color::AnsiValue(56),
        BlueViolet => style::Color::AnsiValue(57),
        // Orange4 => style::Color::AnsiValue(58),
        Grey37 => style::Color::AnsiValue(59),
        MediumPurple4 => style::Color::AnsiValue(60),
        // SlateBlue3 => style::Color::AnsiValue(61),
        SlateBlue3 => style::Color::AnsiValue(62),
        RoyalBlue1 => style::Color::AnsiValue(63),
        Chartreuse4 => style::Color::AnsiValue(64),
        // DarkSeaGreen4 => style::Color::AnsiValue(65),
        PaleTurquoise4 => style::Color::AnsiValue(66),
        SteelBlue => style::Color::AnsiValue(67),
        SteelBlue3 => style::Color::AnsiValue(68),
        CornflowerBlue => style::Color::AnsiValue(69),
        // Chartreuse3 => style::Color::AnsiValue(70),
        DarkSeaGreen4 => style::Color::AnsiValue(71),
        // CadetBlue => style::Color::AnsiValue(72),
        CadetBlue => style::Color::AnsiValue(73),
        SkyBlue3 => style::Color::AnsiValue(74),
        // SteelBlue1 => style::Color::AnsiValue(75),
        Chartreuse3 => style::Color::AnsiValue(76),
        // PaleGreen3 => style::Color::AnsiValue(77),
        SeaGreen3 => style::Color::AnsiValue(78),
        Aquamarine3 => style::Color::AnsiValue(79),
        MediumTurquoise => style::Color::AnsiValue(80),
        SteelBlue1 => style::Color::AnsiValue(81),
        // Chartreuse2 => style::Color::AnsiValue(82),
        SeaGreen2 => style::Color::AnsiValue(83),
        // SeaGreen1 => style::Color::AnsiValue(84),
        SeaGreen1 => style::Color::AnsiValue(85),
        // Aquamarine1 => style::Color::AnsiValue(86),
        DarkSlateGray2 => style::Color::AnsiValue(87),
        DarkRed => style::Color::AnsiValue(88),
        DeepPink4 => style::Color::AnsiValue(89),
        // DarkMagenta => style::Color::AnsiValue(90),
        DarkMagenta => style::Color::AnsiValue(91),
        DarkViolet => style::Color::AnsiValue(92),
        // Purple => style::Color::AnsiValue(93),
        Orange4 => style::Color::AnsiValue(94),
        LightPink4 => style::Color::AnsiValue(95),
        Plum4 => style::Color::AnsiValue(96),
        // MediumPurple3 => style::Color::AnsiValue(97),
        MediumPurple3 => style::Color::AnsiValue(98),
        SlateBlue1 => style::Color::AnsiValue(99),
        // Yellow4 => style::Color::AnsiValue(100),
        Wheat4 => style::Color::AnsiValue(101),
        Grey53 => style::Color::AnsiValue(102),
        LightSlateGrey => style::Color::AnsiValue(103),
        MediumPurple => style::Color::AnsiValue(104),
        LightSlateBlue => style::Color::AnsiValue(105),
        Yellow4 => style::Color::AnsiValue(106),
        DarkOliveGreen3 => style::Color::AnsiValue(107),
        DarkSeaGreen => style::Color::AnsiValue(108),
        // LightSkyBlue3 => style::Color::AnsiValue(109),
        LightSkyBlue3 => style::Color::AnsiValue(110),
        SkyBlue2 => style::Color::AnsiValue(111),
        Chartreuse2 => style::Color::AnsiValue(112),
        // DarkOliveGreen3 => style::Color::AnsiValue(113),
        PaleGreen3 => style::Color::AnsiValue(114),
        DarkSeaGreen3 => style::Color::AnsiValue(115),
        DarkSlateGray3 => style::Color::AnsiValue(116),
        SkyBlue1 => style::Color::AnsiValue(117),
        Chartreuse1 => style::Color::AnsiValue(118),
        // LightGreen => style::Color::AnsiValue(119),
        LightGreen => style::Color::AnsiValue(120),
        // PaleGreen1 => style::Color::AnsiValue(121),
        Aquamarine1 => style::Color::AnsiValue(122),
        DarkSlateGray1 => style::Color::AnsiValue(123),
        // Red3 => style::Color::AnsiValue(124),
        // DeepPink4 => style::Color::AnsiValue(125),
        MediumVioletRed => style::Color::AnsiValue(126),
        // Magenta3 => style::Color::AnsiValue(127),
        // DarkViolet => style::Color::AnsiValue(128),
        Purple => style::Color::AnsiValue(129),
        // DarkOrange3 => style::Color::AnsiValue(130),
        // IndianRed => style::Color::AnsiValue(131),
        // HotPink3 => style::Color::AnsiValue(132),
        MediumOrchid3 => style::Color::AnsiValue(133),
        MediumOrchid => style::Color::AnsiValue(134),
        // MediumPurple2 => style::Color::AnsiValue(135),
        DarkGoldenrod => style::Color::AnsiValue(136),
        // LightSalmon3 => style::Color::AnsiValue(137),
        RosyBrown => style::Color::AnsiValue(138),
        Grey63 => style::Color::AnsiValue(139),
        MediumPurple2 => style::Color::AnsiValue(140),
        MediumPurple1 => style::Color::AnsiValue(141),
        // Gold3 => style::Color::AnsiValue(142),
        DarkKhaki => style::Color::AnsiValue(143),
        NavajoWhite3 => style::Color::AnsiValue(144),
        Grey69 => style::Color::AnsiValue(145),
        LightSteelBlue3 => style::Color::AnsiValue(146),
        LightSteelBlue => style::Color::AnsiValue(147),
        // Yellow3 => style::Color::AnsiValue(148),
        // DarkOliveGreen3 => style::Color::AnsiValue(149),
        // DarkSeaGreen3 => style::Color::AnsiValue(150),
        // DarkSeaGreen2 => style::Color::AnsiValue(151),
        LightCyan3 => style::Color::AnsiValue(152),
        LightSkyBlue1 => style::Color::AnsiValue(153),
        GreenYellow => style::Color::AnsiValue(154),
        DarkOliveGreen2 => style::Color::AnsiValue(155),
        PaleGreen1 => style::Color::AnsiValue(156),
        DarkSeaGreen2 => style::Color::AnsiValue(157),
        // DarkSeaGreen1 => style::Color::AnsiValue(158),
        PaleTurquoise1 => style::Color::AnsiValue(159),
        Red3 => style::Color::AnsiValue(160),
        DeepPink3 => style::Color::AnsiValue(161),
        // DeepPink3 => style::Color::AnsiValue(162),
        // Magenta3 => style::Color::AnsiValue(163),
        Magenta3 => style::Color::AnsiValue(164),
        // Magenta2 => style::Color::AnsiValue(165),
        DarkOrange3 => style::Color::AnsiValue(166),
        IndianRed => style::Color::AnsiValue(167),
        HotPink3 => style::Color::AnsiValue(168),
        HotPink2 => style::Color::AnsiValue(169),
        Orchid => style::Color::AnsiValue(170),
        // MediumOrchid1 => style::Color::AnsiValue(171),
        Orange3 => style::Color::AnsiValue(172),
        LightSalmon3 => style::Color::AnsiValue(173),
        LightPink3 => style::Color::AnsiValue(174),
        Pink3 => style::Color::AnsiValue(175),
        Plum3 => style::Color::AnsiValue(176),
        Violet => style::Color::AnsiValue(177),
        Gold3 => style::Color::AnsiValue(178),
        LightGoldenrod3 => style::Color::AnsiValue(179),
        Tan => style::Color::AnsiValue(180),
        MistyRose3 => style::Color::AnsiValue(181),
        Thistle3 => style::Color::AnsiValue(182),
        Plum2 => style::Color::AnsiValue(183),
        Yellow3 => style::Color::AnsiValue(184),
        Khaki3 => style::Color::AnsiValue(185),
        // LightGoldenrod2 => style::Color::AnsiValue(186),
        LightYellow3 => style::Color::AnsiValue(187),
        Grey84 => style::Color::AnsiValue(188),
        LightSteelBlue1 => style::Color::AnsiValue(189),
        Yellow2 => style::Color::AnsiValue(190),
        // DarkOliveGreen1 => style::Color::AnsiValue(191),
        DarkOliveGreen1 => style::Color::AnsiValue(192),
        DarkSeaGreen1 => style::Color::AnsiValue(193),
        Honeydew2 => style::Color::AnsiValue(194),
        LightCyan1 => style::Color::AnsiValue(195),
        Red1 => style::Color::AnsiValue(196),
        DeepPink2 => style::Color::AnsiValue(197),
        // DeepPink1 => style::Color::AnsiValue(198),
        DeepPink1 => style::Color::AnsiValue(199),
        Magenta2 => style::Color::AnsiValue(200),
        Magenta1 => style::Color::AnsiValue(201),
        OrangeRed1 => style::Color::AnsiValue(202),
        // IndianRed1 => style::Color::AnsiValue(203),
        IndianRed1 => style::Color::AnsiValue(204),
        // HotPink => style::Color::AnsiValue(205),
        HotPink => style::Color::AnsiValue(206),
        MediumOrchid1 => style::Color::AnsiValue(207),
        DarkOrange => style::Color::AnsiValue(208),
        Salmon1 => style::Color::AnsiValue(209),
        LightCoral => style::Color::AnsiValue(210),
        PaleVioletRed1 => style::Color::AnsiValue(211),
        Orchid2 => style::Color::AnsiValue(212),
        Orchid1 => style::Color::AnsiValue(213),
        Orange1 => style::Color::AnsiValue(214),
        SandyBrown => style::Color::AnsiValue(215),
        LightSalmon1 => style::Color::AnsiValue(216),
        LightPink1 => style::Color::AnsiValue(217),
        Pink1 => style::Color::AnsiValue(218),
        Plum1 => style::Color::AnsiValue(219),
        Gold1 => style::Color::AnsiValue(220),
        // LightGoldenrod2 => style::Color::AnsiValue(221),
        LightGoldenrod2 => style::Color::AnsiValue(222),
        NavajoWhite1 => style::Color::AnsiValue(223),
        MistyRose1 => style::Color::AnsiValue(224),
        Thistle1 => style::Color::AnsiValue(225),
        Yellow1 => style::Color::AnsiValue(226),
        LightGoldenrod1 => style::Color::AnsiValue(227),
        Khaki1 => style::Color::AnsiValue(228),
        Wheat1 => style::Color::AnsiValue(229),
        Cornsilk1 => style::Color::AnsiValue(230),
        Grey100 => style::Color::AnsiValue(231),
        Grey3 => style::Color::AnsiValue(232),
        Grey7 => style::Color::AnsiValue(233),
        Grey11 => style::Color::AnsiValue(234),
        Grey15 => style::Color::AnsiValue(235),
        Grey19 => style::Color::AnsiValue(236),
        Grey23 => style::Color::AnsiValue(237),
        Grey27 => style::Color::AnsiValue(238),
        Grey30 => style::Color::AnsiValue(239),
        Grey35 => style::Color::AnsiValue(240),
        Grey39 => style::Color::AnsiValue(241),
        Grey42 => style::Color::AnsiValue(242),
        Grey46 => style::Color::AnsiValue(243),
        Grey50 => style::Color::AnsiValue(244),
        Grey54 => style::Color::AnsiValue(245),
        Grey58 => style::Color::AnsiValue(246),
        Grey62 => style::Color::AnsiValue(247),
        Grey66 => style::Color::AnsiValue(248),
        Grey70 => style::Color::AnsiValue(249),
        Grey74 => style::Color::AnsiValue(250),
        Grey78 => style::Color::AnsiValue(251),
        Grey82 => style::Color::AnsiValue(252),
        Grey85 => style::Color::AnsiValue(253),
        Grey89 => style::Color::AnsiValue(254),
        Grey93 => style::Color::AnsiValue(255),
    }
}
